### ISSUE TITLE
What's your favourite coffee?

### ISSUE THREAD

**Issue by midudev** [sapegin/ama#1]
Coffee with milk? Latte? Espresso? :)

**Comment by sapegin** [comment]
Black, only black! Otherwise I’m not very picky: if it’s not too sour, too bitter or way too strong it’s fine for me. So I prefer americano to espresso.

Thanks for the first question! ☕️

**Comment by midudev** [comment]
Thanks to you for answering! :)

**Comment by havenchyk** [comment]
@sapegin do you have a coffee machine? (I think it shouldn't be a new issue :) )

**Comment by sapegin** [comment]
@havenchyk I have a cheap filter machine at home but don’t tell anyone 🤐
