### ISSUE TITLE
Is it Okay to translate your article and post it on my blog?

### ISSUE THREAD

**Issue by eatnug** [sapegin/ama#16]
Hi, I'm a just-start frontend developer. 
Struggling on how should I test my code, I found your [article](https://blog.sapegin.me/all/react-testing-1-best-practices/) about modern react testing, and I found it quite helpful. So I think it would be helpful too, to translate it and make more developers could read it. 

if you have any opinion, notice me :)

**Comment by sapegin** [comment]
Hey! Sure, just put a link to the original article ;-)

**Comment by eatnug** [comment]
Thanks a lot :)
