### ISSUE TITLE
Is there rss subscription offered by your blog?

### ISSUE THREAD

**Issue by heyyong** [sapegin/ama#17]
Hi, I like your article. But i'm not find your rss entry.

Is there rss subscription offered?

Thx.

**Comment by sapegin** [comment]
Hey!

How are you trying to use it? There's [a feed](https://blog.sapegin.me/atom.xml) and a link to it in the code, so RSS readers should be able to find it.

**Comment by heyyong** [comment]
That's work, thank you.

How about put a rss link on your blog index?

Just search "rss" keyword at https://blog.sapegin.me/ but found nothing.

**Comment by heyyong** [comment]
> Hey!
> 
> How are you trying to use it? There's [a feed](https://blog.sapegin.me/atom.xml) and a link to it in the code, so RSS readers should be able to find it.

All the feeds are manually added by me and assigned to atom.xml....

**Comment by sapegin** [comment]
Good point! I've added a link to the footer.
