### ISSUE TITLE
Can AI help with some of the woes of OSS maintainers

### ISSUE THREAD

**Issue by nischalj10** [sapegin/ama#20]
Hey Artem, I recently read your blog https://dev.to/sapegin/why-i-quit-open-source-1n2e and could not help but wonder why are not there tools that can help maintainers automatically classify spam contributions, do auto PR reviews based on the guidelines of the repo, etc. especially now AI can very well do a lot of these tasks to a decent accuracy. Would love to hear your thoughts on AI for solving some of the problems in OSS ecosystem.

**Comment by sapegin** [comment]
Hey Nischal, I'm actually wondering the same in the article ;-) I don't know if there are any third party tools but I feel like GitHub is't really interested in maintainer mental health — there are surprisingly few tools that help with this. There are plenty of tools to produce more code (like Copilot) but not enough (if any) to deal with it later ;-( 

And I agree with you that AI in it's current state could already do a lot to help in this area...

**Comment by nischalj10** [comment]
True @sapegin, I think there is a lot of gaps that can be addressed by AI. Maintainer mental health is often overlooked :/
