### ISSUE TITLE
How do I send the node data to the terminal using Cypress-Axe

### ISSUE THREAD

**Issue by Joe----** [sapegin/ama#21]
Hi, I can see the node target values in the browser console, and I can send some output to the terminal with 
`cy.task('log','message') `
But, I'd like to output the target values from the nodes for each violation. That way I can find the location when running Cypress headless. Could you possibly share an example?

Thanks!

**Comment by Joe----** [comment]
I think I have it working, but can you let me know if there's a better way?

```
violation.nodes.forEach(({ target }) =>{
  cy.task('log',target.toString())
})
```

**Comment by sapegin** [comment]
This isn't cypress-axe support forum, please ask in the project repository.
