### ISSUE TITLE
What does cypress-axe actually run?

### ISSUE THREAD

**Issue by w4dd325** [sapegin/ama#22]
Hey Artem, 
As the maintainer of cypress-axe, do you have a definitive list of the accessibility checks that get completed when cy.checkA11y() is triggered? 

I would like to compare the A11y checks covered in cypress-axe to the checks that are covered in Accessibility Insights for Web to see if any are duplicated when completing A11y testing.

tia

**Comment by sapegin** [comment]
Hey, these kind of questions would be off-topic here.
