### ISSUE TITLE
What's your feeling about Germany

### ISSUE THREAD

**Issue by havenchyk** [sapegin/ama#3]
Hi Artem @sapegin, glad I can ask you. I'm following you for a couple of years on twitter, but I missed your moving to Germany, I know a lot of people are moving there, but could you please  share your experience? Maybe you can compare living in Russia (Moscow) with Germany.
Why you decided to move?

Thanks in advance!

**Comment by sapegin** [comment]
Hey @havenchyk, thanks for asking!

Actually I never thought about Germany before I started to search a job in Europe. Berlin probably has more jobs for developers than any other city in Europe. It also has very good salary to living cost balance.

I like it so far. It’s smaller than Moscow, cleaner, greener, people usually live closer to work and don’t stay in the office until late evening, weather is a bit warmer, public transport is actually usable, and many other simple things.

Of course not everything is great here: for example mobile plans and internet are very expensive and quality isn’t any better.

The most difficult thing for me is German. You surely can survive in Berlin without but it’s often uncomfortable.

**Comment by havenchyk** [comment]
Thanks for the detailed reply, I've been to Berlin a couple of weeks ago for 5 days and I'd say it's pretty nice. Almost everybody from my friends said that Berlin is dark and not very clean, but I think it depends on the part of city you're living. Please, fix me if I'm wrong :)

as a continue, did you leave Russia just because of new job?

and just wondering, what's the tax in Germany in your case? (in percent to the whole brutto salary)

**Comment by sapegin** [comment]
It depends on a district and on a city you compare to. I’d say it’s cleaner than Moscow but not super clean. Same for darkness: it’s not darker than Moscow but right now at 4pm it’s already dark.

I found a new job to leave Russia ;-)

Taxes here are [a bit crazy](https://github.com/ewgRa/de_faq/blob/master/%D0%9D%D0%B0%D0%BB%D0%BE%D0%B3%D0%B8.md), if you’re interested in numbers here’s [a calculator](http://www.brutto-netto-rechner.info/gehalt/gross_net_calculator_germany.php) (I have a 3rd category).

**Comment by havenchyk** [comment]
Thanks
