### ISSUE TITLE
Can you give advice for mastering UX/UI design?

### ISSUE THREAD

**Issue by ashgaliyev** [sapegin/ama#7]
Hi, Artem!

Currently, I'm creating websites on php + js (both frontend and backend). But I want to switch to frontend development with a bit of UX/UI design.

Can you give advice for mastering UX/UI design?

**Comment by sapegin** [comment]
Sorry, I’ve missed this question somehow ;-|

I’m not a designer, I’m a developer who thinks that design is important for any frontend developer.

Not sure I can answer this question better than I did in my article [What to learn in 2017 if you’re a frontend developer](http://blog.sapegin.me/all/what-to-learn-in-2017):

---

As frontend developers we’re closer to users than anybody else in the team, maybe even closer than designers. And if designers have to verify every pixel you put on screen, you’re doing something wrong.

* Design for Hackers: [a book](https://www.amazon.com/Design-Hackers-Reverse-Engineering-Beauty-ebook/dp/B005J578EW/?tag=artesapesphot-20) and [a free course](https://designforhackers.com/).
* [Design for Non-Designers](https://youtu.be/ZbrzdMaumNk) talk by Tracy Osborn.
* [Design of Web Applications](http://nathanbarry.com/webapps/) book by Nathan Barry.
* [On Web Typography](https://abookapart.com/products/on-web-typography) book by Jason Santa Maria.
* [The Inmates Are Running the Asylum: Why High Tech Products Drive Us Crazy and How to Restore the Sanity](https://www.amazon.com/Inmates-Are-Running-Asylum-Products-ebook/dp/B000OZ0N62/?tag=artesapesphot-20) by Alan Cooper
* A few articles on animation in UI: [How to Use Animation to Improve UX](http://babich.biz/how-to-use-animation-to-improve-ux/), [Transitional Interfaces](https://medium.com/@pasql/transitional-interfaces-926eb80d64e3#.igcwawszz).

---

Also learning to think about UI as component composition may help — splitting UIs into many small highly reusable component will make it more consistent and speed up implementation of new features.

**Comment by andreivoronin** [comment]
Books: Jeff Raskin, Alan Cooper, Steve Krug, Jakob Nielsen, Donald Norman

**Comment by ashgaliyev** [comment]
@sapegin  Thank you for the answer!
